FROM node:23.1.0-bookworm-slim AS build

ARG REACT_APP_MACHINE_IP

ENV REACT_APP_MACHINE_IP=${REACT_APP_MACHINE_IP}

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:23.1.0-alpine

WORKDIR /app

COPY --from=build /app/build /app/build

EXPOSE 3000

CMD ["npx", "serve", "-s", "build"]
