FROM node:23.1.0-bookworm-slim AS build

ARG REACT_APP_MACHINE_IP

ENV REACT_APP_MACHINE_IP=${REACT_APP_MACHINE_IP}

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

#builds the static files to run the application
RUN npm run build

#makes the static files accessable over http
#RUN npm install -g serve

##########################################################
FROM node:23.1.0-alpine

WORKDIR /app

COPY --from=build /app/build /app/build

EXPOSE 3000

CMD ["npx", "serve", "-s", "build"]
