---
- name: Deploy application with Docker Compose
  hosts: all
  become: yes

  vars:
    app_directory_git: "/home/admin/webapp"
    script_name: "machine_ip.sh"
    machine_ip: "{{ machine_ip }}"
  tasks:
    - name: Create a directory for cloning
      ansible.builtin.file:
        path: '/home/admin/webapp'
        state: directory

    - name: Clone the GitHub repository
      git:
        repo: "https://github.com/nivav1/Project_1.git"
        dest: "/home/admin/webapp"
        update: yes

    - name: Export environment variables and run Docker Compose to start the application
      shell: |
        export machine_ip="{{ machine_ip }}"
        docker compose up -d
      args:
        executable: /bin/bash
        chdir: "{{ app_directory_git }}"
