services:
  frontend:
    build:
      context: ./frontend
      args:
       REACT_APP_MACHINE_IP: "${machine_ip}"
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: niv
      POSTGRES_PASSWORD: niv123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U niv -d mydb -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
