services:
  frontend:
    build:
      context: ./frontend
      args:
        - MACHINE_IP=${machine_ip}
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://niv:niv123@db:5432/mydb
    depends_on:
      - db


  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: niv
      POSTGRES_PASSWORD: niv123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
