FROM debian:bookworm-slim

WORKDIR /dependencies

RUN mkdir -p /.aws \
	     /etc/ansible \
	     /.ssh

# /.aws and /.ssh folders removed for security
COPY ./scripts/ ./
COPY ./.aws/* /root/.aws/ 
COPY ./ansible.cfg /etc/ansible/
COPY ./.ssh/id_ed25519* /root/.ssh/

RUN chmod 600 -R /root/.ssh
RUN chmod 600 -R /root/.aws

RUN apt update -y && apt install -y git
RUN bash ./terraforminstall.sh
RUN bash ./ansibleinstall.sh

ENV PATH="${PATH}:/root/.local/bin"

CMD ['']
