services:
  jenkins:
    image: jenkins/jenkins:2.462.3-lts-jdk17
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
volumes:
  jenkins_home:
